services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - chirp-network

  client:
    build: 
      context: .
      dockerfile: Client/Dockerfile
    depends_on:
      - api
    networks:
      - chirp-network

  tweet-posting:
    build: 
      context: .
      dockerfile: TweetPostingService/Dockerfile
    depends_on:
      - api
      - tweet-database
    networks:
      - chirp-network

  tweet-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: iLuvTweets4ever<3
      ACCEPT_EULA: "Y"
    ports:
      - "1401:1433"
    volumes:
      - ./data/tweetdb:/var/opt/mssql/data
    networks:
      - chirp-network

  user-profile:
    build:
      context: .
      dockerfile: UserProfileService/Dockerfile
    depends_on:
      - api
      - user-database
    networks:
      - chirp-network

  user-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: iLuvUsers4ever<3
      ACCEPT_EULA: "Y"
    ports:
      - "1402:1433"
    volumes:
      - ./data/userdb:/var/opt/mssql/data
    networks:
      - chirp-network

networks:
  chirp-network:
    driver: bridge
