services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  client:
    build: 
      context: .
      dockerfile: Client/Dockerfile
    depends_on:
      - api

  tweet-posting:
    build: 
      context: .
      dockerfile: TweetPostingService/Dockerfile
    depends_on:
      - api
      - tweet-database

  tweet-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: iLuvTweets4ever<3
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data

  user-profile:
    build:
      context: .
      dockerfile: UserProfileService/Dockerfile
    depends_on:
      - api
      - user-database

  user-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: iLuvUsers4ever<3
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1434"
    volumes:
      - ./data:/var/opt/mssql/data
